version: '3'
services:
  game_service:
    image: rummi_game
    ports:
      - 8802:8802
    networks:
      default:
        aliases:
          - game

  player_service:
    image: rummi_player
    ports:
            - 8801:8801
    networks:
      default:
        aliases:
          - player
